# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: BlendLuxCore Blender Bundles

on:
  pull_request:
  push:
    branches:
      - for_blender_4.2_wheels
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_bundles:
    name: Build bundles
    runs-on: ubuntu-latest

    steps:

      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Prepare Blender install
        uses: gerlero/apt-install@v1
        with:
          packages: libxxf86vm1 libxfixes3 libxi6 libxkbcommon0 libgl1

      - name: Prepare Python
        run: touch requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: moguri/setup-blender@v1
        with:
          blender-version: '4.2.4'

      - uses: lukka/get-cmake@latest

      - name: Package bundle
        shell: bash
        run: |
          build_dir="${{ github.workspace }}/build"
          mkdir ${build_dir}
          cmake -B ${build_dir} -S .
          cmake --build ${build_dir}
          unzip -q "${build_dir}/BlendLuxCore-*.zip" -d "${{ github.workspace }}/unzip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "BlendLuxCore"
          path: "${{ github.workspace }}/unzip/*"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: ${{ github.workspace }}/build/BlendLuxCore-*.zip
